### ISSUE TITLE
"No contracts found for this project." warning

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/e-skGovCRP#6]
The DPU logs several "No contracts found for this project." warnings. Is this expected?

**Comment by pgo-eea-sk** [comment]
That means that there is not Contracts (Zmluvy) section included in that project

**Comment by jindrichmynarz** [comment]
Is that an error or just a warning that an optional part of data is missing?

**Comment by pgo-eea-sk** [comment]
I don't know the specification of CRP web page, so I can not tell you if Contracts is mandatory part. I can only assume, that it is not if it is missing sometimes. The warning only tells you, that the Contract part is not included in the project record.

**Comment by jindrichmynarz** [comment]
OK, thanks for elaborating.
